server:
  port: 8088

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/workReportDB?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: Pwd2024_
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
  devtools:
    restart:
      exclude: static/**
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload:
    path: E:/15Code/6Java项目/workReport/src/main/resources/upload

#配置mybatis-plus
mybatis-plus:
  global-config:
    banner: off
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置jwt
jwt:
  secret: XoNia7NqrnOhQEOaP7VV2RgGagNKh+iLzj2U9s8Xsus=
  expiration: 3600  #过期时间，单位秒